/**
 * Regenerates the autogenerated regions of the agent skills:
 *  - `omnigraph` SKILL.md: a condensed schema reference (from the SDL bundled with enssdk) and the
 *    vetted example queries (imported directly from the ensnode-sdk source).
 *  - `enscli` SKILL.md: the example commands, imported from the enscli source and grouped into one
 *    `AUTOGEN` region per command section.
 *
 * The single sources are integration-tested in their owning packages, so the skills only ship
 * queries/commands that actually run.
 *
 * Run via `pnpm -F ensskills generate` (wired into the root `pnpm generate`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import prettier from "prettier";

import { buildCondensedSchemaReference } from "@ensnode/ensnode-sdk/internal";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const SKILL_PATH = resolve(SCRIPT_DIR, "../skills/omnigraph/SKILL.md");
const EXAMPLE_QUERIES_PATH = resolve(
  SCRIPT_DIR,
  "../../ensnode-sdk/src/omnigraph-api/example-queries.ts",
);
const ENSCLI_SKILL_PATH = resolve(SCRIPT_DIR, "../skills/enscli/SKILL.md");
const ENSCLI_EXAMPLE_COMMANDS_PATH = resolve(SCRIPT_DIR, "../../enscli/src/example-commands.ts");

interface ExampleQuery {
  id: string;
  title: string;
  description: string;
  query: string;
  variables: { default: Record<string, unknown> };
}

interface EnscliExample {
  id: string;
  comment: string;
  args: string[];
  group: string;
}

async function buildExamples(): Promise<string> {
  // load dynamically to avoid tsconfig root error
  const { GRAPHQL_API_EXAMPLE_QUERIES } = (await import(EXAMPLE_QUERIES_PATH)) as {
    GRAPHQL_API_EXAMPLE_QUERIES: ExampleQuery[];
  };
  // Skip "hello-world": it's the playground welcome blurb, not a reusable query pattern.
  return GRAPHQL_API_EXAMPLE_QUERIES.filter((example) => example.id !== "hello-world")
    .map((example) => {
      if (!example.title?.trim()) {
        throw new Error(`GraphQL API example "${example.id}" is missing a title`);
      }
      if (!example.description?.trim()) {
        throw new Error(`GraphQL API example "${example.id}" is missing a description`);
      }
      const query = example.query.trim();
      const variables = JSON.stringify(example.variables.default, null, 2);
      return [
        `### ${example.title} (${example.id})`,
        example.description,
        "```graphql",
        query,
        "```",
        "Variables:",
        "```json",
        variables,
        "```",
      ].join("\n");
    })
    .join("\n\n");
}

/** Renders an argv element as a shell token, single-quoting anything that isn't plainly bare-safe. */
function shellQuote(arg: string): string {
  if (/^[A-Za-z0-9_./:-]+$/.test(arg)) return arg;
  return `'${arg.replace(/'/g, `'\\''`)}'`;
}

async function buildEnscliExamplesByGroup(): Promise<Map<string, string>> {
  const { ENSCLI_EXAMPLE_COMMANDS } = (await import(ENSCLI_EXAMPLE_COMMANDS_PATH)) as {
    ENSCLI_EXAMPLE_COMMANDS: EnscliExample[];
  };
  const byGroup = new Map<string, EnscliExample[]>();
  for (const example of ENSCLI_EXAMPLE_COMMANDS) {
    const examples = byGroup.get(example.group) ?? [];
    examples.push(example);
    byGroup.set(example.group, examples);
  }
  const rendered = new Map<string, string>();
  for (const [group, examples] of byGroup) {
    const block = examples
      .map(
        (example) => `# ${example.comment}\nnpx enscli ${example.args.map(shellQuote).join(" ")}`,
      )
      .join("\n\n");
    rendered.set(group, ["```bash", block, "```"].join("\n"));
  }
  return rendered;
}

function replaceRegion(content: string, region: string, replacement: string, path: string): string {
  const start = `<!-- AUTOGEN:${region} start -->`;
  const end = `<!-- AUTOGEN:${region} end -->`;
  const pattern = new RegExp(
    `${start.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`,
  );
  if (!pattern.test(content)) {
    throw new Error(`Missing AUTOGEN region "${region}" in ${path}`);
  }
  return content.replace(pattern, `${start}\n${replacement}\n${end}`);
}

/**
 * Writes a SKILL.md, formatted with Prettier so the output matches the linted committed state.
 * Without this the raw region markdown drifts from `pnpm lint` (Prettier reflows markdown), so every
 * `pnpm generate` would leave a noisy, lint-only diff.
 */
async function writeFormatted(path: string, content: string): Promise<void> {
  const options = await prettier.resolveConfig(path);
  writeFileSync(path, await prettier.format(content, { ...options, filepath: path }));
}

async function main(): Promise<void> {
  let content = readFileSync(SKILL_PATH, "utf8");
  content = replaceRegion(content, "SCHEMA", buildCondensedSchemaReference(), SKILL_PATH);
  content = replaceRegion(content, "EXAMPLES", await buildExamples(), SKILL_PATH);
  await writeFormatted(SKILL_PATH, content);
  console.log(`Updated ${SKILL_PATH}`);

  let enscliContent = readFileSync(ENSCLI_SKILL_PATH, "utf8");
  for (const [group, block] of await buildEnscliExamplesByGroup()) {
    enscliContent = replaceRegion(enscliContent, group, block, ENSCLI_SKILL_PATH);
  }
  await writeFormatted(ENSCLI_SKILL_PATH, enscliContent);
  console.log(`Updated ${ENSCLI_SKILL_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
