packages:
  - apps/*
  - docs/*
  - packages/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@ponder/client": ^0.9.23
  "@ponder/react": ^0.9.23
  "@ponder/utils": ^0.2.3
  "@types/node": ^20.10.0
  "@vitest/coverage-v8": ^3.0.5
  drizzle-orm: ^0.39.3
  hono: ^4.6.14
  typescript: ^5.7.3
  viem: ^2.22.13
  vitest: ^3.0.5
  ponder: ^0.9.23
  tsup: ^8.3.6
