packages:
  - apps/*
  - docs/*
  - packages/*

catalog:
  "@adraffy/ens-normalize": 1.11.1
  "@astrojs/react": ^4.4.1
  "@astrojs/tailwind": ^6.0.2
  "@namehash/namekit-react": 0.12.0
  "@ponder/client": 0.16.1
  "@ponder/utils": 0.2.16
  "@testing-library/react": ^16.3.0
  "@types/node": 24.10.9
  astro: ^5.15.9
  astro-font: ^1.1.0
  astro-seo: ^0.8.4
  caip: 1.1.1
  date-fns: 4.1.0
  drizzle-orm: 0.41.0
  hono: ^4.11.4
  lucide-react: ^0.548.0
  pg-connection-string: ^2.9.1
  pino: 10.1.0
  ponder: 0.16.1
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^3.4.0
  tsup: ^8.3.6
  typescript: ^5.7.3
  viem: ^2.22.13
  vite: ^7.1.12
  vitest: ^4.0.2
  zod: ^3.25.7
