packages:
  - apps/*
  - docs/*
  - packages/*

catalog:
  '@astrojs/react': ^4.2.0
  '@astrojs/tailwind': ^6.0.0
  '@biomejs/biome': ^1.9.4
  '@namehash/namekit-react': 0.12.0
  '@ponder/utils': 0.2.10
  '@types/node': ^22.14.0
  '@vitest/coverage-v8': ^3.1.1
  astro-font: ^1.0.0
  astro-seo: ^0.8.4
  date-fns: ^4.1.0
  drizzle-orm: '=0.41.0'
  hono: ^4.7.6
  ponder: 0.11.43
  tsup: ^8.5.0
  typescript: ^5.9.2
  viem: ^2.22.13
  vitest: ^3.1.1
  zod: ^3.25.7
