services:
  ensindexer:
    container_name: ensindexer
    image: ghcr.io/namehash/ensnode/ensindexer:latest
    environment:
      # Override DATABASE_URL to point to docker compose postgres
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      # Override ENSRAINBOW_URL to point to docker compose ensrainbow
      ENSRAINBOW_URL: http://ensrainbow:3223
    env_file:
      # NOTE: must define apps/ensindexer/.env.local (see apps/ensindexer/.env.local.example)
      # Copy .env.local.example to .env.local and configure all required values
      - path: ./apps/ensindexer/.env.local
        required: true
    depends_on:
      - ensrainbow
      - postgres

  ensapi:
    container_name: ensapi
    image: ghcr.io/namehash/ensnode/ensapi:latest
    ports:
      - "4334:4334"
    environment:
      # Override DATABASE_URL to point to docker compose postgres
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    env_file:
      # NOTE: must define apps/ensapi/.env.local (see apps/ensapi/.env.local.example)
      # Copy .env.local.example to .env.local and configure all required values
      - path: ./apps/ensapi/.env.local
        required: true
    depends_on:
      ensindexer:
        condition: service_started
      postgres:
        condition: service_started

  ensrainbow:
    container_name: ensrainbow
    image: ghcr.io/namehash/ensnode/ensrainbow:latest
    ports:
      - "3223:3223"
    env_file:
      # NOTE: can define apps/ensrainbow/.env.local (see apps/ensrainbow/.env.local.example)
      - path: ./apps/ensrainbow/.env.local
        required: false
    restart: unless-stopped

  ensadmin:
    container_name: ensadmin
    image: ghcr.io/namehash/ensnode/ensadmin:latest
    ports:
      - "4173:4173"
    environment:
      ENSADMIN_PUBLIC_URL: http://localhost:4173
      # Override NEXT_PUBLIC_SERVER_CONNECTION_LIBRARY to the docker compose ensapi
      # Note: it must be a comma-separated list of URLs that are accessible from a web browser
      # (i.e. it cannot be a hostname in the docker network)
      NEXT_PUBLIC_SERVER_CONNECTION_LIBRARY: http://localhost:42069
    env_file:
      # NOTE: can define apps/ensadmin/.env.local (see apps/ensadmin/.env.local.example)
      - path: ./apps/ensadmin/.env.local
        required: false
    depends_on:
      - ensapi

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
