services:
  ensindexer:
    container_name: ensindexer
    image: ghcr.io/namehash/ensnode/ensindexer:stable
    pull_policy: always
    ports:
      - "42069:42069"
    environment:
      # Override DATABASE_URL to point to docker compose postgres
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      # Override ENSRAINBOW_URL to point to docker compose ensrainbow
      ENSRAINBOW_URL: http://ensrainbow:3223
      # Override ENSADMIN_URL to point to docker compose ensadmin
      ENSADMIN_URL: http://localhost:4321
      # Override ENSNODE_PUBLIC_URL to point to docker compose ensadmin
      ENSNODE_PUBLIC_URL: http://localhost:42069
      # NOTE: must define indexing behavior in .env.local (see .env.local.example)
    env_file:
      - ./.env.local
    depends_on:
      - ensrainbow
      - postgres

  ensrainbow:
    container_name: ensrainbow
    image: ghcr.io/namehash/ensnode/ensrainbow:latest
    pull_policy: always
    ports:
      - "3223:3223"
    env_file:
      - ./.env.local
    restart: unless-stopped

  ensadmin:
    container_name: ensadmin
    image: ghcr.io/namehash/ensnode/ensadmin:latest
    pull_policy: always
    ports:
      - "4173:4173"
    environment:
      VITE_ENSNODE_URL: http://ensindexer:42069
    env_file:
      - ./.env.local
    depends_on:
      - ensindexer

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
