name: 'Setup Node Environment'
description: 'Sets up pnpm, Node.js, and optionally installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: useblacksmith/setup-node@v5
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
