name: 'Setup Node Environment'
description: 'Sets up pnpm, Node.js, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: useblacksmith/setup-node@v5
      with:
        node-version-file: .nvmrc
        # NOTE: This registry-url is required so NODE_AUTH_TOKEN / NPM_TOKEN work for npm auth,
        # especially in workflows that publish packages. Do not remove unless auth is no longer needed.
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
