name: 'Setup Node Environment'
description: 'Sets up pnpm, Node.js, and optionally installs dependencies'
inputs:
  install-dependencies:
    description: 'Run pnpm install --frozen-lockfile'
    required: false
    default: 'false'
  registry-url:
    description: 'Optional registry URL for npm publishing (passed to setup-node). Required for publishing, not for general CI scripting.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: useblacksmith/setup-node@v5
      with:
        node-version-file: .nvmrc
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
