# Base working stage
FROM node:18-slim AS base

FROM base as working-stage
RUN apt-get update && \
    npm install -g pnpm
###################
## Dependencies Stage — standard monorepo pnpm install from base
###################
WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY packages ./packages
COPY apps ./apps

RUN pnpm install --silent
###################
## Data Stage — download ENS Subgraph rainbow table archive & checksum
###################
RUN apt-get install -y wget
COPY apps/ensrainbow/package.json apps/ensrainbow/download-rainbow-tables.sh ens_names.sql.gz* ./apps/ensrainbow/

WORKDIR /app/apps/ensrainbow
RUN pnpm get-legacy-data
###################
## Runtime Stage — ingest to produce data dir artifact
###################
# produce the data dir artifact
RUN pnpm run ingest

###################
## Output Image — just the data dir
###################
FROM base AS ensrainbow-data

COPY --from=working-stage /app/apps/ensrainbow/data ./data
