services:
  ensadmin:
    container_name: ensadmin
    image: ghcr.io/namehash/ensnode/ensadmin:latest
    build:
      dockerfile: ./apps/ensadmin/Dockerfile
      context: ../..
    ports:
      - "4173:4173"
    depends_on:
      ensapi:
        condition: service_started
