name: Build Docker image
description: builds multi-arch docker image

inputs:
  image_name:
    description: 'Target Docker image name'
    required: true

  dockerfile_path:
    description: 'Target Dockerfile path'
    required: true

  registry_user:
    description: 'Username for Docker registry'
    required: true

  registry_token:
    description: 'Registry token for Docker registry authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_name }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.registry_user }}
        password: ${{ inputs.registry_token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile_path }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
