name: Build ENSRainbow-data image

on: workflow_dispatch

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make disk space ( remove unnecessary libs )
        run: |
            # Remove Android libs
            sudo rm -rf /usr/local/lib/android || true
            # Remove dotnet libs
            sudo rm -rf /usr/share/dotnet || true

      - name: Set up QEMU (for cross-architecture builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      

      - name: Build and push ENSRainbow-data Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/ensrainbow/Dockerfile.data
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ghcr.io/${{ github.repository }}/ensrainbow-data:${{ matrix.arch }}
