name: "Build: ENSRainbow v2 image"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  image-build-and-push:
    if: false
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Set up QEMU (for cross-architecture builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image for the ENSRainbow v2 app
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/ensrainbow-v2
          TAG: latest
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64 -f apps/ensrainbow/Dockerfile --build-arg DATA_IMAGE_NAME=ensrainbow-v2-data -t $IMAGE_NAME:$TAG  .
