name: "Build: ENSIndexer"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.release.tag_name, 'ensindexer') }}
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: ./.github/actions/build_docker_image
        with:
          image: ghcr.io/${{ github.repository }}/ensindexer
          dockerfile: apps/ensindexer/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
