name: Build ENSIndexer image

on:
  push:
    branches:
      - main
      - feat/445-add-versioning-for-ensnode-2
    tags:
      - '@ensnode/ensindexer*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
      - name: Extract metadata for Docker
        id: meta
        run: |
          # Set default tag as latest
          DOCKER_TAG="dev"
          
          # If this is a tag push, use the tag name instead
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            DOCKER_TAG=${GITHUB_REF#refs/tags/@ensnode/ensindexer@}
          fi
          echo "tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

      - name: Build and push ENSIndexer Docker image
        if: steps.publish-meta.outputs.ensindexer_version != ''
        uses: ./.github/actions/build_docker_image
        with:
          image_name:  ghcr.io/${{ github.repository }}/ensindexer:${{ env.tag }}  
          dockerfile_path: apps/ensindexer/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }} 
