name: Build ENSAdmin image

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU (for cross-architecture builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build & Push Docker image for the ENSAdmin app
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/ensadmin
          TAG: latest
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --push --platform linux/amd64,linux/arm64 -f apps/ensadmin/Dockerfile -t $IMAGE_NAME:$TAG  .
