name: "Build: ENSAdmin"

on:
  workflow_dispatch:
  push:
    tags:
      - 'ensadmin@*'

jobs:
  build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: ./.github/actions/build_docker_image
        with:
          image: ghcr.io/${{ github.repository }}/ensadmin
          dockerfile: apps/ensadmin/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
