name: "Build: ENSIndexer"

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Build and push ENSIndexer Docker image
        uses: ./.github/actions/build_docker_image
        with:
          image_name:  ghcr.io/${{ github.repository }}/ensindexer
          dockerfile_path: apps/ensindexer/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
