name: "Build: ENSRainbow"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [created, published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Build & Push Docker image for the ENSRainbow app
        uses: ./.github/actions/build_docker_image
        with:
          image_name:  ghcr.io/${{ github.repository }}/ensrainbow
          dockerfile_path: apps/ensrainbow/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
