name: "Build: ENSRainbow-test-data"

on:
  workflow_dispatch:

jobs:
  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image for the ENSRainbow-test-data
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/ensrainbow-test-data
          TAG: latest
        run: |
          docker buildx build --push -f apps/ensrainbow/Dockerfile.data --build-arg DATA_VERSION=test -t $IMAGE_NAME:$TAG .
