name: Build ENSRainbow-data image

on: workflow_dispatch

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make disk space ( remove unnecessary libs )
        run: |
            # Show disk usage
            echo "Before cleanup"
            df -h
            # Remove dotnet, android, ghc, codeq directories, boost
            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/hostedtoolcache/CodeQ /usr/local/share/boost
            # Show disk usage
            echo "After cleanup"
            df -h

      - name: Set up QEMU (for cross-architecture builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push ENSRainbow-data Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/ensrainbow/Dockerfile.data
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}/ensrainbow-data:latest
