name: Build ENSAdmin image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [created, published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Extract metadata for Docker
        id: meta
        run: |
          # Set default tag as latest
          DOCKER_TAG="latest"
          # If this is a tag push, use the tag name instead
          if [[ $GITHUB_REF == refs/tags/ensadmin@* ]]; then
            DOCKER_TAG=${GITHUB_REF#refs/tags/ensadmin@}
          fi
          echo "tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image for the ENSAdmin app
        uses: ./.github/actions/build_docker_image
        env:
          TAG: ${{ steps.meta.outputs.tag }}
        with:
          image_name:  ghcr.io/${{ github.repository }}/ensadmin:${{ env.TAG }}
          dockerfile_path: apps/ensadmin/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
