name: Build ENSRainbow image

on:
  push:
    branches:
      - main
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}
          
jobs:

  image-build-and-push:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      
      - name: Extract metadata for Docker
        id: meta
        run: |
          # Set default tag as latest
          DOCKER_TAG="latest"
          # If this is a tag push, use the tag name instead
          if [[ $GITHUB_REF == refs/tags/ensrainbow@* ]]; then
            DOCKER_TAG=${GITHUB_REF#refs/tags/ensrainbow@}
          fi
          echo "tag=$DOCKER_TAG" >> $GITHUB_OUTPUT
  
      - name: Build & Push Docker image for the ENSRainbow app
        uses: ./.github/actions/build_docker_image
        env:
          TAG: ${{ steps.meta.outputs.tag }}
        with:
          image_name:  ghcr.io/${{ github.repository }}/ensrainbow:${{ env.TAG }}
          dockerfile_path: apps/ensrainbow/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }} 
