name: Create GitHub Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    # Only run when PR is merged (not just closed) and has the title "Release New Version"
    # Note the title is set in the release.yml workflow as changeset-action@v1 inputs.title
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Release New Version'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from PR description
        id: extract-version
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # Try to extract version from any package
          # Note: all packages are released with the same version (see .changeset/config.json->fixed)
          VERSION=$(echo "$PR_BODY" | grep -o '@[^@]*@[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1 | awk -F@ '{print $3}')

          
          # If still no version found, exit with error
          if [ -z "$VERSION" ]; then
            echo "ERROR: Could not extract version number from PR description"
            exit 1
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract-version.outputs.version }}
          name: Release v${{ steps.extract-version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
