name: "Release: ENSNode"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-packages:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm packages:prepublish

      - name: Publish Packages
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-push-ensnode:
    name: ${{ matrix.app_name }} ${{ matrix.ensrainbow_data_image }}
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        include:
          # ensindexer
          - app_name: ensindexer
          # ensadmin
          - app_name: ensadmin
          # ensrainbow v1
          - app_name: ensrainbow
            ensrainbow_data_image: ensrainbow-data
          # ensrainbow v2
          - app_name: ensrainbow
            ensrainbow_data_image: ensrainbow-v2-data
          # ensrainbow test
          - app_name: ensrainbow
            ensrainbow_data_image: ensrainbow-test-data

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build & Push
        uses: ./.github/actions/build_docker_image
        with:
          image: ghcr.io/${{ github.repository }}/${{ matrix.app_name }}
          dockerfile: apps/${{ matrix.app_name }}/Dockerfile
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            DATA_IMAGE_NAME=${{ matrix.ensrainbow_data_image }}
