name: Test ENSRainbow Test Image on Ubuntu ARM

on:
  workflow_dispatch:

jobs:
  test-image-on-ubuntu-arm:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Verify Docker installation
        run: |
          docker --version
          docker info
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull ENSRainbow test image
        run: |
          docker pull --platform linux/arm64 ghcr.io/namehash/ensnode/ensrainbow-test:latest
      
      - name: Run ENSRainbow test container
        run: |
          # Run the container in detached mode with explicit platform
          CONTAINER_ID=$(docker run --platform linux/arm64 -d -p 3223:3223 ghcr.io/namehash/ensnode/ensrainbow-test:latest)
          echo "Container ID: $CONTAINER_ID"
          
          # Wait for container to start up
          echo "Waiting for container to start up..."
          sleep 30
          
          # Check container logs
          echo "Container logs:"
          docker logs $CONTAINER_ID
          
          # Check if container is running
          CONTAINER_STATUS=$(docker inspect --format='{{.State.Status}}' $CONTAINER_ID)
          echo "Container status: $CONTAINER_STATUS"
          
          if [ "$CONTAINER_STATUS" != "running" ]; then
            echo "Container is not running!"
            exit 1
          fi
          
          # Test API endpoint
          echo "Testing API endpoint..."
          curl -v http://localhost:3223/health || exit 1
          
          # Stop and remove container
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
      
      - name: Report test results
        if: always()
        run: |
          echo "ENSRainbow test image verification completed"
          # Add any additional reporting or notifications here 
