name: "Test: ENSRainbow Test Image on macOS"

on:
  workflow_dispatch:

jobs:
  test-image-on-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_buildx: true

      - name: Verify Docker installation
        run: |
          docker --version
          docker info

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull ENSRainbow test image
        run: |
          docker pull ghcr.io/namehash/ensnode/ensrainbow:latest

      - name: Run ENSRainbow test container
        run: |
          # Create a directory on your host machine for test data
          mkdir -p ~/my_ensrainbow_test_data

          # Run the container in detached mode
          CONTAINER_ID=$(docker run -d \
            -v ~/my_ensrainbow_test_data:/app/apps/ensrainbow/data \
            -e DB_SCHEMA_VERSION="3" \
            -e LABEL_SET_ID="ens-test-env" \
            -e LABEL_SET_VERSION="0" \
            -p 3223:3223 \
            ghcr.io/namehash/ensnode/ensrainbow:latest)
          echo "Container ID: $CONTAINER_ID"

          # Wait for container to start up
          echo "Waiting for container to start up..."
          sleep 30

          # Check container logs
          echo "Container logs:"
          docker logs $CONTAINER_ID

          # Check if container is running
          CONTAINER_STATUS=$(docker inspect --format='{{.State.Status}}' $CONTAINER_ID)
          echo "Container status: $CONTAINER_STATUS"

          if [ "$CONTAINER_STATUS" != "running" ]; then
            echo "Container is not running!"
            exit 1
          fi

          # Test API endpoint
          echo "Testing API endpoint..."
          curl -v http://localhost:3223/health || exit 1

          # Stop and remove container
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID

      - name: Report test results
        if: always()
        run: |
          echo "ENSRainbow test image verification completed"
          # Add any additional reporting or notifications here
